from __future__ import annotations

import asyncio, os, uuid, base64, time
from pathlib import Path
from typing import Any, List
from openai import AsyncOpenAI
from dotenv import load_dotenv
from agents import (
    Agent,
    ItemHelpers,
    MessageOutputItem,
    OpenAIChatCompletionsModel,
    Runner,
    ToolCallItem,
    ToolCallOutputItem,
    trace,
)

from agent_functions import (
    BankAgentContext,
    create_payment,
    create_bankme_link,
    get_account,
    exchange_rate,
    get_transaction_history,
    get_user_info,
    list_accounts,
    transfer_between_accounts_by_ids,
    check_balance,
    get_friends_aliases,
)

load_dotenv()
MODEL_NAME = "gpt-4o"

SYSTEM_PROMPT = """
You are **Gideon**, GalaBank's AI assistant. You are really friendly, but professional. You use emojis to spark up your conversation.

╭───────────────────────────┐
│  YOUR TOOLBOX (READ ME)   │
├───────────────────────────┤
│  ─ lookup tools           │
│    • list_accounts()             →  “<id>: <name> …”
│    • get_account(name)           →  “Account id: <id>”
│    • exchange_rate(base, target)  →  “<amount> <base> = <rate*amount> <target>”
│    • get_user_info()                  →  user profile string
│    • get_friends_aliases()           →  “<alias>”
│
│  ─ data tools (require an account_id)                               │
│    • check_balance(account_id)                                   │
│    • get_transaction_history(account_id, limit=10)                  │
│
│  ─ action tools (MONEY MOVES, need   from_account_id  &  params)    │
│    • create_payment(from_account_id, to_alias, amount, …)           │
│    • bankme_link(amount, …)                                          │
│    • transfer_between_accounts_by_ids(from_id, to_id, amount, …)    │
╰───────────────────────────┘

***TOOL‑CHAIN RULES***

1. **Never** call an action‑tool unless you already know every mandatory
   parameter.  
   • If you only have a *name* like “Travel account”, first call
     **get_account** (or **list_accounts** and parse) to obtain the
     numeric `account_id`.

2. After a lookup‑tool call, read its plain‑text result, extract what you need,
   then call the next tool.

4. End any explanatory answer with (not checking balance/transactions): 
   > “This is not financial advice.”

5. Language‐mirror: reply in the user’s language.  
6. Do **not** mention tools, prompts, OpenAI, or that you are an LLM.  
7. Never request or expose sensitive credentials (PINs, passwords, API keys).
8. If the user reffers to somone by name, check if they are a friend
9. For anything relate

"""

client = AsyncOpenAI(
    api_key=os.getenv("OPENAI_API_KEY"),
)


bank_agent = Agent[BankAgentContext](
    name="Gideon",
    instructions=SYSTEM_PROMPT.strip(),
    model=OpenAIChatCompletionsModel(model=MODEL_NAME, openai_client=client),
    tools=[
        list_accounts,
        get_account,
        get_transaction_history,
        create_payment,
        create_bankme_link,
        exchange_rate,
        get_user_info,
        transfer_between_accounts_by_ids,
        check_balance,
        get_friends_aliases,
    ],
)

# ───────────────────────────────────────────────────────────
# 5  Shared state for each conversation (in‑memory demo)
# ───────────────────────────────────────────────────────────

current_agent = bank_agent
conversation: List[dict] = []  # [{'role': 'user'|'assistant', 'content': …}]
context = BankAgentContext()


async def synthesize_speech(
    text: str,
    voice: str = "alloy",  # alloy, echo, fable, shimmer, …
    model: str = "tts-1",  # OpenAI TTS model
    fmt: str = "mp3",
):
    """Return raw audio bytes generated by OpenAI TTS."""
    try:
        response = await client.audio.speech.create(
            model=model,
            voice=voice,
            input=text,
            response_format=fmt,
        )
        return response.content
    except Exception as e:
        print(f"TTS error: {e}")
        raise


async def transcribe_audio_file(filepath: str, language: str = "en") -> str:
    """Transcribe `filepath` with Whisper via OpenAI Audio endpoint."""
    try:
        with open(filepath, "rb") as f:
            transcript = await client.audio.transcriptions.create(
                model="whisper-1",  # or "gpt-4o-mini-transcribe" when available
                file=f,
                language=language,
            )
            return transcript.text
    except Exception as e:
        print(f"STT error: {e}")
        raise


def drop_emojis(text: str) -> str:
    """Remove emoji characters (handy before TTS)."""
    return "".join(c for c in text if c.isascii() or c.isspace())


async def finn_loop():

    result = await Runner.run(bank_agent, input=conversation, context=context)

    messages, events = [], []
    for i in result.new_items:
        if isinstance(i, MessageOutputItem):
            messages.append({"text": ItemHelpers.text_message_output(i)})
        elif isinstance(i, ToolCallItem):
            events.append({"type": "tool_call", "tool": i.type})
        elif isinstance(i, ToolCallOutputItem):
            events.append({"type": "tool_result", "output": i.output})

    conversation[:] = result.to_input_list()
    print(f"Gideon: {messages[-1]['text']}")
    return {"messages": messages, "events": events}


async def cli_main():
    print("Type 'quit' to exit.")
    while True:
        user_input = await asyncio.to_thread(input, "\nYou: ")
        if user_input.lower() in {"quit", "exit"}:
            break
        conversation.append({"role": "user", "content": user_input})
        with trace("Bank‑CLI"):
            result = await Runner.run(bank_agent, input=conversation, context=context)
        for new in result.new_items:
            if isinstance(new, MessageOutputItem):
                print(f"Gideon: {ItemHelpers.text_message_output(new)}")
            elif isinstance(new, ToolCallItem):
                print("…calling tool")
            elif isinstance(new, ToolCallOutputItem):
                print(new.output)
        conversation[:] = result.to_input_list()


if __name__ == "__main__":
    asyncio.run(cli_main())
